"""Relaciones ProductoMarcaPrecio

Revision ID: cc427854e58a
Revises: 
Create Date: 2024-06-25 20:50:46.142860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc427854e58a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('precio_id',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.create_foreign_key(None, 'precio', ['precio_id'], ['id'])
        batch_op.create_foreign_key(None, 'marca', ['marca_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('precio_id',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
